# Generated by Django 6.0.4 on 2026-05-09 14:43

import claims.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0003_remove_food_donor_remove_food_pickup_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_code', models.CharField(default=claims.models.generate_pickup_code, max_length=4, unique=True)),
                ('pickup_code_verified', models.BooleanField(default=False)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='food.food')),
            ],
        ),
    ]
