# Generated by Django 6.0.4 on 2026-05-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked up', 'Picked Up'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
