# Generated by Django 6.0.4 on 2026-06-02 17:06

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='pickup_code',
            field=models.CharField(default=claims.models.generate_pickup_code, max_length=4),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
