# Generated by Django 6.0.4 on 2026-04-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=1024)),
                ('category', models.CharField(choices=[('cooked', 'Cooked'), ('raw', 'Raw'), ('packaged', 'Packaged'), ('other', 'Other')], max_length=1024)),
                ('quantity_estimated', models.PositiveIntegerField()),
                ('quantity_unit', models.CharField(max_length=50)),
                ('pickup_start_time', models.DateTimeField()),
                ('pickup_end_time', models.DateTimeField()),
                ('expiry_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
