# Generated by Django 6.0.4 on 2026-05-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_contact_person_name_food_contact_person_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='food',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='food',
            name='pickup_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='pickup_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='contact_person_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='contact_person_phone',
            field=models.CharField(default=56790643367, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('distributed', 'Distributed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
