# Generated by Django 6.0.4 on 2026-05-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_food_donor_remove_food_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pickup_address',
            field=models.CharField(default=19, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='pickup_city',
            field=models.CharField(default='Accra', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('picked up', 'Picked Up'), ('distributed', 'Distributed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
