# Generated by Django 6.0.4 on 2026-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_pickup_address_alter_food_pickup_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
