# Generated by Django 6.0.4 on 2026-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_food_pickup_latitude_food_pickup_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('distributed', 'Distributed'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
