# Generated by Django 6.0.4 on 2026-05-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0002_alter_claim_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_time', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField()),
                ('households_served', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='claims.claim')),
            ],
        ),
    ]
