# Generated by Django 6.0.4 on 2026-04-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('receiver', 'Receiver'), ('admin', 'Admin')], max_length=20),
        ),
    ]
