# Generated by Django 6.0.4 on 2026-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('catering', 'Catering'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('event_center', 'Event Center'), ('cafeteria', 'Cafeteria'), ('other', 'Other'), ('food_bank', 'Food Bank'), ('ngo', 'NGO'), ('church/mosque', 'Church/mosque'), ('shelter', 'Shelter'), ('community_coordinator', 'Community Coordinator'), ('local_volunteer_group', 'Local Volunteer Group'), ('other', 'Other')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('partner', 'Partner'), ('receiver', 'Receiver')], max_length=20),
        ),
    ]
