# Generated by Django 6.0.4 on 2026-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_organisation_type_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner'), ('receiver', 'Receiver'), ('admin', 'Admin')], max_length=20),
        ),
    ]
