# Generated by Django 6.0.4 on 2026-05-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_latitude_remove_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('catering', 'Catering'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('event center', 'Event Center'), ('cafeteria', 'Cafeteria'), ('other', 'Other'), ('food bank', 'Food Bank'), ('ngo', 'NGO'), ('religious organization', 'Religious Organization'), ('shelter', 'Shelter'), ('community coordinator', 'Community Coordinator'), ('local volunteer group', 'Local Volunteer Group'), ('other', 'Other')], max_length=225, null=True),
        ),
    ]
