# Generated by Django 6.0.4 on 2026-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_organisation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
