# Generated by Django 6.0.4 on 2026-06-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
