# Generated by Django 6.0.4 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
