# Generated by Django 6.0.4 on 2026-06-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_business_verified',
            field=models.BooleanField(default=False),
        ),
    ]
