# Generated by Django 6.0.4 on 2026-06-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_is_verified_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='donor_detail', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('food_safety_certificate_url', models.URLField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ngo_certificate_url', models.URLField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('catering', 'Catering'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('event center', 'Event Center'), ('cafeteria', 'Cafeteria'), ('other', 'Other'), ('food bank', 'Food Bank'), ('ngo', 'NGO'), ('religious organization', 'Religious Organization'), ('shelter', 'Shelter'), ('community coordinator', 'Community Coordinator'), ('local volunteer group', 'Local Volunteer Group'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('partner', 'Partner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
