# Generated by Django 6.0.4 on 2026-06-17 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_donordetails_partnerdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner_detail', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
