# Generated by Django 6.0.4 on 2026-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_partnerdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('catering', 'Catering'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('event_center', 'Event Center'), ('cafeteria', 'Cafeteria'), ('other', 'Other'), ('food_bank', 'Food Bank'), ('ngo', 'NGO'), ('religious_organization', 'Religious Organization'), ('shelter', 'Shelter'), ('community_coordinator', 'Community Coordinator'), ('local_volunteer_group', 'Local Volunteer Group'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
